baseURL = 'https://charao.dev/'
languageCode = 'en-us'
title = 'Thiago Char√£o'
theme = "hello-friend-ng"
paginate     = 10
keywords = ""
menuMore = "Show more"
writtenBy = "Written by"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
minuteReadingTime = "min read"
copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'


[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  logoText = "sudo rm -rf /"
  logoHomeLink = "/"
  # or
  #
  # path = "images/rick.svg"
  # alt = "Your example logo alt text"
  # Subtitle for home
  homeSubtitle = "Director of Architecture"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "thiago, charao, developer, blog, software, engineering"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

# And you can even create generic menu
[[menu.main]]
#  identifier = "blog"
#  name       = "Blog"
#  url        = "/posts"

[[params.social]]
name = "linkedin"
url = "https://linkedin.com/in/charao"

[[params.social]]
name = "twitter"
url = "https://twitter.com/thiagocharao"

[[params.social]]
name = "email"
url = "mailto:thiago@charao.dev"

[[params.social]]
name = "github"
url = "https://github.com/thiagocharao"

